version: "3.8"
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - db-network
  db:
    image: postgres:latest
    restart: unless-stopped
    hostname: db
    volumes:
      - postgres-data-store:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - db-network
  shadow-db:
    image: postgres:latest
    restart: unless-stopped
    hostname: shadow-db
    ports:
      - 5431:5431
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    command: -p 5431
    networks:
      - db-network

volumes:
  postgres-data-store:
networks:
  db-network:
